/* Modernized function prototypes - Generated by analyze_function_signatures.py */

/* else functions */
extern else errormsg("invalid input error");  /* from commands.c:994 */
extern else getjewel(&sct[x][y]);  /* from update.c:1519 */

/* generated message from a hostile NPC to a functions */

/* int functions */
extern int addgroup(int armynum);  /* from extcmds.c:714 */
extern int addgships(int int nvynum, int int shipsize, int int nships);  /* from navy.c:218 */
extern int addmships(int int nvynum, int int shipsize, int int nships);  /* from navy.c:145 */
extern int addwships(int nvynum, int shipsize, int nships);  /* from navy.c:72 */
extern int aretheyon(int void);  /* from main.c:1617 */
extern int armygoto(int void);  /* from commands.c:2204 */
extern int armymove(int int armynum);  /* from update.c:454 */
extern int armyrpt(int repnum);  /* from reports.c:210 */
extern int atkattr(int void);  /* from npc.c:3064 */
extern int att_base(int void);  /* from admin.c:691 */
extern int att_bonus(int void);  /* from admin.c:1003 */
extern int att_setup(int int cntry);  /* from admin.c:572 */
extern int avian(int int typ);  /* from misc.c:1943 */
extern int blowup(int register int i, int register int j);  /* from randeven.c:1809 */
extern int budget(int void);  /* from reports.c:603 */
extern int camp_info(int void);  /* from main.c:1862 */
extern int canbeseen(int int x, int int y);  /* from display.c:976 */
extern int cbonus(int int num);  /* from combat.c:947 */
extern int centermap(int void);  /* from io.c:947 */
extern int change(int void);  /* from forms.c:649 */
extern int change_status(int int armynum, int int new_stat);  /* from extcmds.c:348 */
extern int cheat(int void);  /* from update.c:749 */
extern int check_lock(int char *filename, int int keeplock);  /* from check.c:439 */
extern int check_mail(int void);  /* from misc.c:3455 */
extern int checkout(int char *file, int int line);  /* from check.c:381 */
extern int clear_bottom(int i);  /* from extcmds.c:666 */
extern int coffmap(int void);  /* from display.c:907 */
extern int combat(void);  /* from combat.c:157 */
extern int combinearmies(int int armynum, int int army2);  /* from extcmds.c:264 */
extern int compass(int int x0, int int y0, int int x1, int int y1);  /* from misc.c:3342 */
extern int construct(int void);  /* from commands.c:652 */
extern int copyscreen(int void);  /* from main.c:1666 */
extern int credits(int void);  /* from main.c:1792 */
extern int defattr(int void);  /* from npc.c:2968 */
extern int defaultunit(int int nation);  /* from misc.c:3057 */
extern int deplete(int int nation);  /* from misc.c:1426 */
extern int destroy(int int cntry);  /* from misc.c:1609 */
extern int diploscrn(int void);  /* from forms.c:411 */
extern int do_lizard(int void);  /* from update.c:1148 */
extern int do_nomad(int void);  /* from npc.c:464 */
extern int do_pirate(int void);  /* from npc.c:672 */
extern int do_savage(int void);  /* from npc.c:573 */
extern int domagic(int void);  /* from magic.c:391 */
extern int draft(int void);  /* from commands.c:1119 */
extern int errorbar(int char *str1, int char *str2);  /* from newlogin.c:699 */
extern int erupt(int void);  /* from randeven.c:1708 */
extern int execute(int isupdate);  /* from cexecute.c:119 */
extern int exenewmgk(int long newpower);  /* from magic.c:654 */
extern int ext_cmd(int armie);  /* from extcmds.c:113 */
extern int fight(int void);  /* from combat.c:391 */
extern int fill_edge(int int AX, int int AY);  /* from makeworl.c:1020 */
extern int flee(int int x, int int y, int int isupd, int int slaver);  /* from io.c:1275 */
extern int fleetrpt(int void);  /* from reports.c:1003 */
extern int flightcost(int int i, int int j);  /* from misc.c:1920 */
extern int fltghold(int int nvynum);  /* from navy.c:768 */
extern int flthold(int int nvynum);  /* from navy.c:641 */
extern int fltmhold(int int nvynum);  /* from navy.c:829 */
extern int fltships(int int country, int int nvynum);  /* from navy.c:507 */
extern int fltspeed(int int nvynum);  /* from navy.c:572 */
extern int fltwhold(int int nvynum);  /* from navy.c:706 */
extern int fort_val(int struct s_sector *sptr);  /* from misc.c:3314 */
extern int get_country(int void);  /* from misc.c:2372 */
extern int get_god(int void);  /* from misc.c:2494 */
extern int get_nname(int char str[]);  /* from misc.c:2261 */
extern int get_number(int void);  /* from misc.c:160 */
extern int get_pass(int char *str);  /* from io.c:1602 */
extern int getclass(int int race);  /* from newlogin.c:2153 */
extern int getdstatus(int void);  /* from npc.c:1289 */
extern int getleader(int int class);  /* from misc.c:2591 */
extern int getmagic(int type);  /* from magic.c:185 */
extern int getmetal(int struct s_sector *sptr);  /* from misc.c:3073 */
extern int getmgkcost(int int type, int int nation);  /* from misc.c:1251 */
extern int getnewname(int int new);  /* from randeven.c:613 */
extern int getselunit(int void);  /* from move.c:785 */
extern int getspace(void);  /* from io.c:177 */
extern int hangup(int void);  /* from cexecute.c:417 */
extern int help(int void);  /* from forms.c:1076 */
extern int highlight(int int x, int int y, int short hmode);  /* from display.c:814 */
extern int is_habitable(int int x, int int y);  /* from misc.c:926 */
extern int jump_to(int int home);  /* from io.c:1023 */
extern int land_2reachp(int int ax, int int ay, int int move_points);  /* from misc.c:280 */
extern int land_reachp(int int ax, int int ay, int int gx, int int gy, int int move_points, int int movee);  /* from misc.c:497 */
extern int loadfleet(int void);  /* from navy.c:1057 */
extern int mailclose(int int to);  /* from misc.c:2822 */
extern int mailopen(int int to);  /* from misc.c:2689 */
extern int makebottom(void);  /* from main.c:675 */
extern int makemap(int void);  /* from display.c:291 */
extern int monster(int void);  /* from npc.c:275 */
extern int moveciv(int void);  /* from commands.c:2031 */
extern int mymove(void);  /* from move.c:127 */
extern int n_toofar(int void);  /* from npc.c:2120 */
extern int n_trespass(int void);  /* from npc.c:2023 */
extern int n_unowned(int void);  /* from npc.c:2232 */
extern int nationrun(int void);  /* from npc.c:1655 */
extern int navalcbt(int void);  /* from combat.c:1308 */
extern int navygoto(int void);  /* from commands.c:2346 */
extern int newbye(int int status);  /* from newlogin.c:538 */
extern int newdip(int int ntn1, int int ntn2);  /* from npc.c:191 */
extern int newdisplay(int void);  /* from display.c:508 */
extern int newerror(int char *str);  /* from newlogin.c:605 */
extern int newinit(int void);  /* from newlogin.c:421 */
extern int newlogin(int int realuser);  /* from newlogin.c:1071 */
extern int newmsg(int char *str);  /* from newlogin.c:596 */
extern int newreset(int void);  /* from newlogin.c:484 */
extern int newspaper(int void);  /* from forms.c:1312 */
extern int num_powers(int int nation, int int type);  /* from misc.c:1070 */
extern int offmap(int void);  /* from io.c:823 */
extern int orctake(int int *count);  /* from magic.c:997 */
extern int parse(int int ch);  /* from main.c:758 */
extern int pceattr(int void);  /* from npc.c:3164 */
extern int populate(int void);  /* from makeworl.c:1135 */
extern int pr_desg(int void);  /* from io.c:472 */
extern int pr_ntns(int void);  /* from io.c:398 */
extern int prep(int int nation, int int leader);  /* from misc.c:1306 */
extern int printele(int void);  /* from io.c:331 */
extern int printscore(int void);  /* from io.c:1155 */
extern int printveg(int void);  /* from io.c:549 */
extern int produce(int void);  /* from reports.c:792 */
extern int rand_sector(int void);  /* from randeven.c:1861 */
extern int randomevent(int void);  /* from randeven.c:702 */
extern int readdata(int void);  /* from io.c:712 */
extern int readmap(int void);  /* from io.c:1412 */
extern int redesignate(int void);  /* from commands.c:299 */
extern int redomil(int void);  /* from npc.c:868 */
extern int reduce(int int x, int int y, int int percent);  /* from randeven.c:1832 */
extern int reducearmy(int int armynum, int int men);  /* from extcmds.c:479 */
extern int removemgk(int long oldpower);  /* from magic.c:1251 */
extern int reset_god(int void);  /* from misc.c:2581 */
extern int rmessage(int void);  /* from commands.c:1530 */
extern int sackem(int int cntry);  /* from misc.c:1518 */
extern int score(int void);  /* from update.c:686 */
extern int score_one(int int nation);  /* from misc.c:862 */
extern int see(int int x, int int y);  /* from display.c:747 */
extern int showscore(void);  /* from forms.c:194 */
extern int solds_in_sector(int int x, int int y, int int nation);  /* from misc.c:757 */
extern int splitarmy(int armynum);  /* from extcmds.c:571 */
extern int spreadsheet(int int nation);  /* from misc.c:2041 */
extern int subgships(int int nvynum, int int shipsize, int int nships);  /* from navy.c:436 */
extern int submships(int int nvynum, int int shipsize, int int nships);  /* from navy.c:364 */
extern int subwships(int int nvynum, int int shipsize, int int nships);  /* from navy.c:291 */
extern int takeover(int int percent, int int target);  /* from magic.c:551 */
extern int tg_ok(int int nation, int struct s_sector *sptr);  /* from misc.c:3214 */
extern int todigit(int register int character);  /* from misc.c:1294 */
extern int tofood(int struct s_sector *sptr, int int cntry);  /* from misc.c:1153 */
extern int units_in_sector(int int x, int int y, int int nation);  /* from misc.c:998 */
extern int unitvalid(int int type);  /* from magic.c:1114 */
extern int update(int void);  /* from update.c:150 */
extern int updcapture(int void);  /* from update.c:1296 */
extern int updcomodities(int void);  /* from update.c:2181 */
extern int updexecs(int void);  /* from update.c:892 */
extern int updleader(int void);  /* from update.c:2379 */
extern int updmil(int void);  /* from update.c:1795 */
extern int updmove(int int race, int int cntry);  /* from misc.c:1798 */
extern int updsectors(int void);  /* from update.c:1499 */
extern int verify_sct(int char __file__[], int int __line__);  /* from check.c:251 */
extern int verifydata(int char __file__[], int int __line__);  /* from check.c:337 */
extern int water_2reachp(int int ax, int int ay, int int move_points);  /* from misc.c:623 */
extern int water_reachp(int int ax, int int ay, int int gx, int int gy, int int move_points, int int movee);  /* from misc.c:723 */
extern int wdisaster(int int cntry, int int xloc, int int yloc, int int prcnt, int char *event);  /* from randeven.c:1382 */
extern int weather(int void);  /* from randeven.c:1877 */
extern int whatcansee(int void);  /* from display.c:1033 */
extern int wizardry(int void);  /* from magic.c:1582 */
extern int wmessage(int void);  /* from commands.c:1764 */
extern int writedata(int void);  /* from io.c:624 */

/* long functions */

/* return functions */

/* static int functions */

/* static void functions */

/* void functions */
extern void init_hasseen(void);  /* from main.c:128 */
extern void makemess(int count, FILE *output);  /* from spew.c:252 */
extern void place(void);  /* from sort.c:123 */

/* Functions declared in data.h but not found in source files */
/* MISSING: adjarm - void adjarm */
/* MISSING: bye - void bye */
/* MISSING: createworld - void createworld */
/* MISSING: doclass - int doclass */
/* MISSING: fdxyretreat - void fdxyretreat */
/* MISSING: m2alloc - char	**m2alloc(void) */
/* MISSING: makeside - void	makeside(int alwayssee) */
/* MISSING: makeworld - void makeworld */
/* MISSING: markok - int markok */
/* MISSING: move_file - int move_file */
/* MISSING: n_atpeace - void n_atpeace */
/* MISSING: n_people - void n_people */
/* MISSING: npcredes - void npcredes */
/* MISSING: other_revolt - int other_revolt(int *new) */
/* MISSING: peasant_revolt - void peasant_revolt(int *newnation) */
/* MISSING: printnat - void printnat */
/* MISSING: rawmaterials - void rawmaterials */
/* MISSING: retreat - void retreat */
/* MISSING: startcost - int startcost */
/* MISSING: verify_ntn - void verify_ntn */

/* Functions with multiple definitions (need review) */
/* DUPLICATE: if found in: */
/*   combat.c:410 - else if(ntn[anation].dstatus[owner[j]]==JIHAD) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:411 - else if(ntn[owner[j]].dstatus[anation]==JIHAD) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:412 - else if(ntn[anation].dstatus[owner[j]]==WAR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:413 - else if(ntn[owner[j]].dstatus[anation]==WAR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:414 - else if((ntn[owner[j]].dstatus[anation]==TREATY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:415 - else if((ntn[owner[j]].dstatus[anation]==ALLIED) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:456 - else if(side[i]==ATKR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:481 - else if(dsold > asold*100) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:532 - else if(side[i]==DFND && ntn[owner[i]].arm[unit[i]].stat!=RULE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:544 - else if(side[i]==DFND) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:563 - else if((ntn[owner[i]].arm[unit[i]].unittyp == A_CATAPULT) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:576 - else if((ntn[owner[i]].arm[unit[i]].unittyp == A_SIEGE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:611 - else if(dstr > astr*100) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:662 - else if(retreatside==DFND) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:770 - else if(loss==DFND) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:772 - else if(loss==WIMP) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:806 - else if(loss==DFND) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:818 - else if(side[k]==ATKR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:836 - else if((ntn[UOWNER(k) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:970 - else if(sct[xspot][yspot].altitude==HILL) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:973 - else if(sct[xspot][yspot].vegetation==FOREST) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:974 - else if(sct[xspot][yspot].vegetation==WOOD) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:980 - else if(ASTAT==SORTIE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:981 - else if(ASTAT==SIEGED) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:990 - else if(side[num]==ATKR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:1026 - else if((ATYPE == A_ARCHER) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:1028 - else if(ATYPE == A_ARCHER) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:1333 - else if(ntn[anation].dstatus[owner[j]]==JIHAD) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:1334 - else if(ntn[owner[j]].dstatus[anation]==JIHAD) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:1335 - else if(ntn[anation].dstatus[owner[j]]==WAR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:1336 - else if(ntn[owner[j]].dstatus[anation]==WAR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:1337 - else if((ntn[owner[j]].dstatus[anation]==TREATY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:1339 - else if((ntn[owner[j]].dstatus[anation]==ALLIED) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:1436 - else if(dcrew > acrew*100) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:1725 - else if(side[j]==DFND) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:1748 - else if(side[j]==DFND) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   combat.c:1756 - else if(side[k]==ATKR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   commands.c:491 - else if((newdes == DCITY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   commands.c:701 - else if(sct[XREAL][YREAL].designation==DFORT) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   commands.c:702 - else if(sct[XREAL][YREAL].designation==DCAPITOL) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   commands.c:703 - else if(sct[XREAL][YREAL].designation==DCITY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   commands.c:765 - else if(magic(country,SAILOR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   commands.c:896 - int if(int amount<=0) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   commands.c:913 - else if(magic(country,SAILOR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   commands.c:982 - else if(type=='f') */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   commands.c:1192 - else if(ch == '2') */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   commands.c:2046 - else if(sct[XREAL][YREAL].people==0) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   commands.c:2094 - else if(sct[i][j].owner!=country && country!=0) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   commands.c:2096 - else if(sct[i][j].owner!=country) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   main.c:476 - int if(int checkuser_mod) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   main.c:487 - int if(int checkuser_list) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   main.c:1415 - else if(magic(i,THE_VOID) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   main.c:1437 - else if(magic(i,THE_VOID) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   move.c:325 - else if((movecost[XREAL][YREAL]<0) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   move.c:349 - else if((sct[XREAL][YREAL].owner!=country) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:307 - else if(designation==DCITY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:308 - else if(designation==DCAPITOL) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:309 - else if(designation==DTOWN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:310 - else if(designation==DMINE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:320 - else if((designation==DMINE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:322 - else if(designation==DTOWN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:323 - else if(designation==DCITY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:324 - else if(designation==DCAPITOL) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:327 - else if(sptr->vegetation==FOREST) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:330 - else if(sptr->altitude==HILL) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:331 - else if(sptr->altitude==CLEAR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:337 - else if((designation==DMINE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:339 - else if(designation==DTOWN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:340 - else if(designation==DCITY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:341 - else if(designation==DCAPITOL) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:344 - else if(sptr->vegetation==FOREST) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:347 - else if(sptr->altitude==HILL) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:348 - else if(sptr->altitude==CLEAR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:354 - else if((designation==DMINE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:356 - else if(designation==DTOWN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:357 - else if(designation==DCITY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:358 - else if(designation==DCAPITOL) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:361 - else if(sptr->vegetation==FOREST) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:364 - else if(sptr->altitude==HILL) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:365 - else if(sptr->altitude==CLEAR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:371 - else if((designation==DMINE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:373 - else if(designation==DTOWN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:374 - else if(designation==DCITY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:375 - else if(designation==DCAPITOL) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:378 - else if(sptr->vegetation==FOREST) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:381 - else if(sptr->altitude==HILL) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:382 - else if(sptr->altitude==CLEAR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   update.c:1941 - else if(A->smove>4) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   admin.c:729 - else if(d==DCITY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   admin.c:737 - else if(d==DCAPITOL) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   admin.c:741 - else if(d==DROAD) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   admin.c:742 - else if(d==DCHURCH) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   admin.c:743 - else if(d==DGRANARY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   admin.c:744 - else if(d==DBLKSMITH) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   cexecute.c:189 - else if(isneutral(ntn[y].active) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   cexecute.c:190 - else if(npctype(ntn[y].active) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   display.c:582 - else if(tofood( &sct[x+xoffset][y+yoffset],country) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   display.c:595 - else if((country==0) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   display.c:626 - else if(movecost[x+xoffset][y+yoffset]<0) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   display.c:635 - else if(sct[x+xoffset][y+yoffset].altitude==HILL) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   display.c:640 - else if(sct[x+xoffset][y+yoffset].vegetation==FOREST) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   display.c:642 - else if(sct[x+xoffset][y+yoffset].vegetation==WOOD) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   display.c:654 - else if(sct[x+xoffset][y+yoffset].people>=9950) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   display.c:656 - else if(sct[x+xoffset][y+yoffset].people>=4950) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   display.c:658 - else if(sct[x+xoffset][y+yoffset].people>=950) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   display.c:666 - else if(tofood( &sct[x+xoffset][y+yoffset],country) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   display.c:668 - else if(tg_ok(country,&sct[x+xoffset][y+yoffset]) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   display.c:678 - else if(tofood( &sct[x+xoffset][y+yoffset],country) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   display.c:680 - else if(tg_ok(country,&sct[x+xoffset][y+yoffset]) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   display.c:690 - else if(tofood( &sct[x+xoffset][y+yoffset],country) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   forms.c:593 - else if((curntn->dstatus[nation]==TREATY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   forms.c:694 - else if(isnpc( curntn->active) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   forms.c:833 - else if(intval > 20) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   forms.c:835 - else if(intval > 10 && (curntn->tsctrs<20 || curntn->score<20) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   forms.c:884 - else if(intval+curntn->terror > 100) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   forms.c:886 - else if((intval > curntn->popularity) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   forms.c:889 - else if(intval>5) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   forms.c:925 - else if(magic(country,CAPTAIN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   forms.c:926 - else if(magic(country,WARRIOR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   forms.c:1429 - else if(lineno>LINES-4) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   forms.c:1430 - else if(strlen(line) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   io.c:741 - else if(n_read==-1) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   io.c:752 - else if(n_read!= NTOTAL*sizeof(struct s_nation) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   io.c:837 - else if(xcurs >= SCREEN_X_SIZE-1) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   io.c:853 - else if(xcurs >= SCREEN_X_SIZE-1) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   io.c:870 - else if(ycurs >= SCREEN_Y_SIZE-1) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   io.c:886 - else if(ycurs >= SCREEN_Y_SIZE-1) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   io.c:1334 - else if(isupd==0) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   magic.c:218 - else if(magic(country,CAPTAIN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   magic.c:222 - else if(magic(country,WARLORD) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   magic.c:233 - else if(magic(country,AV_MONST) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   magic.c:237 - else if(magic(country,MA_MONST) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   magic.c:311 - else if(isnotpc(curntn->active) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   magic.c:325 - else if((newpower==SUMMON) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   magic.c:443 - else if(countx == 40) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   magic.c:570 - else if(y>=500) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   magic.c:744 - else if(curntn->repro>11) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   magic.c:750 - else if(curntn->repro<=9) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   magic.c:764 - else if(curntn->repro>11) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   magic.c:1026 - else if((curntn->dstatus[i]<HOSTILE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   magic.c:1275 - int if(int sct[x][y].vegetation==DESERT) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   magic.c:1589 - int if(int curntn->spellpts>0) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:733 - int if(int type[x][y]==LAND) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:743 - else if(sct[x][y].altitude==MOUNTAIN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:747 - else if(sct[x][y].altitude==PEAK) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:788 - else if(rand() */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:789 - else if(rand() */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:1053 - else if((area + edgearea) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:1062 - else if((area + edgearea) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:1071 - else if((area + edgearea) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:1080 - else if((area + edgearea) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:1486 - else if(allign == 'N') */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:1488 - else if(allign == 'E') */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:1490 - else if(allign == 'g') */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:1492 - else if(allign == 'n') */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:1494 - else if(allign == 'e') */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   makeworl.c:1496 - else if(allign == 'i') */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:1170 - else if(sptr->vegetation == BARREN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:1260 - else if(ntn[nation].race==HUMAN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:1261 - else if(ntn[nation].race==ORC) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:1268 - else if(ntn[nation].race==HUMAN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:1269 - else if(ntn[nation].race==ORC) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:1276 - else if(ntn[nation].race==ORC) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:1673 - else if(ntn[sct[nptr->capx][nptr->capy].owner].race!=nptr->race) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:2085 - else if(sptr->designation==DFARM) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:2123 - else if(sptr->designation==DGOLDMINE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:2136 - else if((sptr->designation==DCITY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:2155 - else if(((magic(sptr->owner,DERVISH) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:2169 - else if(SEASON(TURN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:2176 - else if(SEASON(TURN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:2276 - else if((ch=='\b' || ch=='\177') */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   misc.c:3365 - else if(dy<0) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   navy.c:1110 - else if(P_NPEOP==0) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   navy.c:1182 - else if(mcargo==0) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   newlogin.c:1092 - int if(int ntn[i].active==INACTIVE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   newlogin.c:2015 - else if(curntn->location==OOPS) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   newlogin.c:2016 - else if(curntn->location==RANDOM) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   newlogin.c:2017 - else if(curntn->location==FAIR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   newlogin.c:2018 - else if(curntn->location==GREAT) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   newlogin.c:2026 - else if(t==2) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   newlogin.c:2510 - else if(curntn->location==GREAT) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:280 - else if(curntn->active==NPC_PIRATE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:281 - else if(curntn->active==NPC_SAVAGE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:282 - else if(curntn->active==NPC_LIZARD) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:794 - else if(( rand() */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:798 - else if(( rand() */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:800 - else if(sptr->people>1000) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:950 - else if(peace==12) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:988 - else if(P_ASOLD *4L > 5L*ideal) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:1142 - else if(P_ASOLD>0 && (P_ASOLD<TAKESECTOR || P_ASTAT==MILITIA) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:1302 - else if(( curntn->active==GOOD_4FREE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:1305 - else if(( curntn->active==GOOD_2FREE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:1308 - else if(( curntn->active==GOOD_0FREE) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:1505 - else if(sptr->jewels != 0) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:1771 - else if(loop>=6) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:1772 - else if(loop>=4) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:1776 - else if(loop>=6) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:1777 - else if(loop>=4) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:1781 - else if(loop>=6) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:1782 - else if(loop>=4) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:1896 - else if((zz=getmagic(M_CIV) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:1912 - else if(magic(country,CAPTAIN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:1913 - else if(magic(country,WARRIOR) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:2254 - else if(sct[x][y].jewels != 0) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:2334 - else if(movecost[x][y]<=3) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   npc.c:2335 - else if(movecost[x][y]<=5) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   randeven.c:853 - else if(magic(country,CAPTAIN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   randeven.c:858 - else if(magic(country,WARLORD) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   randeven.c:983 - else if((is_habitable(xpos,ypos) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   randeven.c:989 - else if(curntn->tmil > 5000) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   randeven.c:991 - else if(curntn->tmil > 1000) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   reports.c:309 - else if((inpkey=='\n') */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   reports.c:475 - else if(men > NOUNITTYPES) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   reports.c:813 - int if(int P_ASOLD>0) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   reports.c:1103 - else if((navy=='\n') */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   reports.c:1148 - else if((P_NARMY!=MAXARM) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   reports.c:1152 - else if((newx==P_NXLOC) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   trade.c:495 - else if(holdint==TDSHIP) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   trade.c:661 - else if(sct[xspot][yspot].owner != country) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   trade.c:665 - else if(curntn->capx==xspot && curntn->capy==yspot) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   trade.c:669 - else if(sct[xspot][yspot].designation == DTOWN) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   trade.c:673 - else if(sct[xspot][yspot].designation == DCITY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   trade.c:1316 - else if(item1==TDLAND) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   trade.c:1318 - else if(item1==TDARMY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   trade.c:1320 - else if(item1==TDSHIP) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   trade.c:1324 - else if(item2==TDLAND) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   trade.c:1326 - else if(item2==TDARMY) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   trade.c:1328 - else if(item2==TDSHIP) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   trade.c:1812 - int if(int deal[holdint]==SELL) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/*   trade.c:1815 - int if(int natn[holdint] == cntry) */
/*   combat.c:409 - else if(owner[j]==dnation) */
/* DUPLICATE: fprintf found in: */
/*   combat.c:1727 - else fprintf(fnews,", neutral %s",ntn[owner[j]].name) */
/*   combat.c:808 - else fprintf(fm,"You are Neutral\n") */
/*   combat.c:1750 - else fprintf(fm,"You are on the Neutral Side\n") */
/*   combat.c:808 - else fprintf(fm,"You are Neutral\n") */
/*   commands.c:1802 - else fprintf(fm,"Message to %s from %s (%s of year %d) */
/*   combat.c:808 - else fprintf(fm,"You are Neutral\n") */
/*   commands.c:1911 - else fprintf(fm,"5.God      :%s\n",line) */
/*   combat.c:808 - else fprintf(fm,"You are Neutral\n") */
/*   main.c:346 - else fprintf(stderr,"What nation would you like to be: ") */
/*   combat.c:808 - else fprintf(fm,"You are Neutral\n") */
/*   misc.c:1626 - else fprintf(fnews,"(they owned their capitol) */
/*   combat.c:808 - else fprintf(fm,"You are Neutral\n") */
/* DUPLICATE: show_ships found in: */
/*   combat.c:1952 - int show_ships(int char *who, int char *what, int int war, int int gal, int int mer) */
/*   combat.c:1326 - void show_ships(void) */
/* DUPLICATE: errormsg found in: */
/*   commands.c:1212 - else errormsg("You gotta be kinding!?  Sailors on land?") */
/*   commands.c:994 - else errormsg("invalid input error") */
/*   commands.c:1242 - else errormsg("error: raising too many soldiers") */
/*   commands.c:994 - else errormsg("invalid input error") */
/*   move.c:329 - else errormsg("Can't Move Here") */
/*   commands.c:994 - else errormsg("invalid input error") */
/*   move.c:503 - else errormsg("Zone Of Control - Reducing Movement") */
/*   commands.c:994 - else errormsg("invalid input error") */
/*   magic.c:1656 - else errormsg("You have no spell points for spell casting") */
/*   commands.c:994 - else errormsg("invalid input error") */
/* DUPLICATE: sect_info found in: */
/*   main.c:1197 - int sect_info(void) */
/*   main.c:764 - void sect_info(void) */
/* DUPLICATE: mvprintw found in: */
/*   main.c:1550 - else mvprintw(LINES-11,COLS-2,"%d",i) */
/*   main.c:1536 - else mvprintw(LINES-12,COLS-20,"owner: %s",ntn[sptr->owner].name) */
/*   main.c:1553 - else mvprintw(LINES-11,COLS-3,"%d",i) */
/*   main.c:1536 - else mvprintw(LINES-12,COLS-20,"owner: %s",ntn[sptr->owner].name) */
/*   navy.c:1091 - else mvprintw(LINES-4,25,"Army (%d) */
/*   main.c:1536 - else mvprintw(LINES-12,COLS-20,"owner: %s",ntn[sptr->owner].name) */
/*   reports.c:360 - else mvprintw(ypos++,0,"Disband your %s %d?",*(unittype+(P_ATYPE%UTYPE) */
/*   main.c:1536 - else mvprintw(LINES-12,COLS-20,"owner: %s",ntn[sptr->owner].name) */
/* DUPLICATE: move_people found in: */
/*   update.c:2575 - int move_people(int void) */
/*   update.c:901 - void move_people(void) */
/* DUPLICATE: main found in: */
/*   admin.c:205 - int main(int int argc, int char **argv) */
/*   main.c:113 - int main(int int argc, int char **argv) */
/*   newhelp.c:132 - int main(int void) */
/*   main.c:113 - int main(int int argc, int char **argv) */
/*   psmap.c:788 - int main(int int argc, int char *argv[]) */
/*   main.c:113 - int main(int int argc, int char **argv) */
/*   sort.c:118 - int main(int int argc, int char *argv[]) */
/*   main.c:113 - int main(int int argc, int char **argv) */
/* DUPLICATE: srand found in: */
/*   admin.c:211 - void srand(void) */
/*   main.c:126 - void srand(void) */
/* DUPLICATE: init_hasseen found in: */
/*   display.c:237 - int init_hasseen(void) */
/*   main.c:128 - void init_hasseen(void) */
/* DUPLICATE: addstr found in: */
/*   extcmds.c:129 - else addstr(", (S) */
/*   commands.c:861 - else addstr("?") */
/*   forms.c:696 - else addstr(" (MON) */
/*   commands.c:861 - else addstr("?") */
/* DUPLICATE: nocomb_stat found in: */
/*   extcmds.c:266 - int nocomb_stat(void) */
/*   extcmds.c:203 - int nocomb_stat(int int astat) */
/* DUPLICATE: mvaddstr found in: */
/*   forms.c:259 - else mvaddstr(ypos+7,xpos,"No") */
/*   move.c:400 - else mvaddstr(LINES-3,0,"Do you wish to invade?") */
/*   forms.c:273 - else mvaddstr(ypos+11,xpos,"No") */
/*   move.c:400 - else mvaddstr(LINES-3,0,"Do you wish to invade?") */
/*   forms.c:753 - else mvaddstr(LINES-4,COLS/2-22,"CANT ADD TO COMBAT BONUS") */
/*   move.c:400 - else mvaddstr(LINES-3,0,"Do you wish to invade?") */
/*   forms.c:761 - else mvaddstr(LINES-3,COLS/2-14,"HIT ANY OTHER KEY TO CONTINUE") */
/*   move.c:400 - else mvaddstr(LINES-3,0,"Do you wish to invade?") */
/*   forms.c:1414 - else mvaddstr(lineno++,0,line+2) */
/*   move.c:400 - else mvaddstr(LINES-3,0,"Do you wish to invade?") */
/*   forms.c:1432 - else mvaddstr(lineno++,0,line+2) */
/*   move.c:400 - else mvaddstr(LINES-3,0,"Do you wish to invade?") */
/*   magic.c:1043 - else mvaddstr((*count) */
/*   move.c:400 - else mvaddstr(LINES-3,0,"Do you wish to invade?") */
/*   magic.c:1476 - else mvaddstr(county++,0,"Which power to add?") */
/*   move.c:400 - else mvaddstr(LINES-3,0,"Do you wish to invade?") */
/*   magic.c:1495 - else mvaddstr(county++,0,"The nation already has that power.") */
/*   move.c:400 - else mvaddstr(LINES-3,0,"Do you wish to invade?") */
/*   trade.c:383 - else mvaddstr(count++,0,"Market Congested.  (B) */
/*   move.c:400 - else mvaddstr(LINES-3,0,"Do you wish to invade?") */
/* DUPLICATE: for found in: */
/*   forms.c:776 - else for(i=1;i<NTOTAL;i++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   makeworl.c:756 - int for(int x=0;x<MAPX;x++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   makeworl.c:761 - else for(n=3;n<10;n++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   makeworl.c:768 - else for(n=3;n<10;n++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   makeworl.c:779 - else for(n=2;n<9;n++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   makeworl.c:791 - else for(n=2;n<4;n++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   makeworl.c:1058 - else for(i=0;i<8;i++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   makeworl.c:1067 - else for(i=0;i<8;i++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   makeworl.c:1076 - else for(i=0;i<8 ;i++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   makeworl.c:1085 - else for(i=0;i<8 ;i++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   navy.c:646 - int for(int i=N_LIGHT;i<=N_HEAVY;i++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   navy.c:710 - int for(int i=N_LIGHT;i<=N_HEAVY;i++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   navy.c:772 - int for(int i=N_LIGHT;i<=N_HEAVY;i++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   navy.c:833 - int for(int i=N_LIGHT;i<=N_HEAVY;i++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   npc.c:315 - int for(int i=0;i<MAXARM;i++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   npc.c:1730 - else for(x=0;x<NTOTAL;x++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   sort.c:179 - int for(int ;j<l && argv[i][j]>='0' && argv[i][j]<='9';j++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/*   trade.c:1810 - int for(int holdint=0; holdint<itemnum; holdint++) */
/*   commands.c:697 - else for(x=1;x<=sct[XREAL][YREAL].fortress;x++) */
/* DUPLICATE: putc found in: */
/*   io.c:414 - else putc(ntn[sct[X][Y].owner].mark,stdout) */
/*   io.c:345 - else putc(' ',stdout) */
/*   io.c:492 - else putc(sct[X][Y].designation,stdout) */
/*   io.c:345 - else putc(' ',stdout) */
/* DUPLICATE: return found in: */
/*   magic.c:226 - else return(0L) */
/*   cexecute.c:375 - else return(0) */
/*   magic.c:241 - else return(0L) */
/*   cexecute.c:375 - else return(0) */
/*   misc.c:3063 - else return(A_URUK) */
/*   cexecute.c:375 - else return(0) */
/*   misc.c:3323 - else return(DEF_BASE + FORTSTR * sptr->fortress) */
/*   cexecute.c:375 - else return(0) */
/*   misc.c:3335 - else return(2*DEF_BASE + CITYSTR * sptr->fortress) */
/*   cexecute.c:375 - else return(0) */
/* DUPLICATE: god_magk found in: */
/*   magic.c:1422 - int god_magk(int void) */
/*   magic.c:396 - void god_magk(void) */
/* DUPLICATE: exenewmgk found in: */
/*   magic.c:1491 - else exenewmgk(powers[choice-1]) */
/*   magic.c:654 - int exenewmgk(int long newpower) */
/* DUPLICATE: dosummon found in: */
/*   magic.c:1586 - void dosummon(void) */
/*   magic.c:858 - int dosummon(int void) */
/* DUPLICATE: readmap found in: */
/*   makeworl.c:339 - else readmap(void) */
/*   io.c:1412 - int readmap(int void) */
/*   psmap.c:503 - int readmap(int void) */
/*   io.c:1412 - int readmap(int void) */
/* DUPLICATE: getjewel found in: */
/*   misc.c:3106 - int getjewel(int struct s_sector *sptr) */
/*   update.c:1519 - else getjewel(&sct[x][y]) */
/*   newlogin.c:274 - else getjewel(&sct[i][j]) */
/*   update.c:1519 - else getjewel(&sct[x][y]) */
/*   newlogin.c:294 - else getjewel(&sct[i][j]) */
/*   update.c:1519 - else getjewel(&sct[x][y]) */
/* DUPLICATE: switch found in: */
/*   npc.c:293 - int switch(int ntn[i].active) */
/*   update.c:1846 - else switch(A->stat) */
/*   trade.c:241 - else switch(holdint) */
/*   update.c:1846 - else switch(A->stat) */
/*   trade.c:900 - int switch(int item) */
/*   update.c:1846 - else switch(A->stat) */
/*   trade.c:980 - int switch(int item) */
/*   update.c:1846 - else switch(A->stat) */
/*   trade.c:1068 - int switch(int item) */
/*   update.c:1846 - else switch(A->stat) */
/* DUPLICATE: printf found in: */
/*   npc.c:952 - else printf("error - incap is %d ideal is %ld\n",P_ASOLD,ideal) */
/*   combat.c:669 - else printf("retreat side %d to %d %d\n",retreatside,retreatx,retreaty) */
/*   npc.c:1009 - else printf("\tno action - P_ASOLD (%d) */
/*   combat.c:669 - else printf("retreat side %d to %d %d\n",retreatside,retreatx,retreaty) */
/*   randeven.c:741 - else printf("revolt in %s fails because:\n\t%s\n",curntn->name,eventstr) */
/*   combat.c:669 - else printf("retreat side %d to %d %d\n",retreatside,retreatx,retreaty) */
/*   randeven.c:756 - else printf("revolt in %s fails because:\n\t%s\n",curntn->name,eventstr) */
/*   combat.c:669 - else printf("retreat side %d to %d %d\n",retreatside,retreatx,retreaty) */
/* DUPLICATE: get_line found in: */
/*   sort.c:281 - int get_line(int char data[]) */
/*   sort.c:122 - int get_line(void) */
/* DUPLICATE: place found in: */
/*   sort.c:380 - int place(int char data[]) */
/*   sort.c:123 - void place(void) */
/* DUPLICATE: comp_line found in: */
/*   sort.c:440 - int comp_line(int char *a, int char *b) */
/*   sort.c:383 - int comp_line(void) */
/* DUPLICATE: load_rules_file found in: */
/*   spew.c:370 - static int load_rules_file(const char *filename) */
/*   spew.c:164 - static int load_rules_file(const char *filename) */
/* DUPLICATE: parse_class_header found in: */
/*   spew.c:511 - static int parse_class_header(const char *line, struct text_class *cls) */
/*   spew.c:165 - static int parse_class_header(const char *line, struct text_class *cls) */
/* DUPLICATE: generate_text found in: */
/*   spew.c:950 - static void generate_text(const char *class_spec, char default_variant, FILE *output) */
/*   spew.c:168 - static void generate_text(const char *class_spec, char variant_tag, FILE *output) */
/* DUPLICATE: read_line found in: */
/*   spew.c:1179 - static int read_line(void) */
/*   spew.c:171 - static int read_line(void) */
/* DUPLICATE: compare_classes found in: */
/*   spew.c:1310 - static int compare_classes(const void *a, const void *b) */
/*   spew.c:172 - static int compare_classes(const void *a, const void *b) */
/* DUPLICATE: cleanup_memory found in: */
/*   spew.c:1558 - static void cleanup_memory(void) */
/*   spew.c:169 - static void cleanup_memory(void) */
/* DUPLICATE: makemess found in: */
/*   spew.c:1584 - void makemess(int count, FILE *output) */
/*   spew.c:252 - void makemess(int count, FILE *output) */
/* DUPLICATE: tradeerr found in: */
/*   trade.c:596 - int tradeerr(int char *mesg) */
/*   trade.c:124 - void tradeerr(void) */
/* DUPLICATE: tradable found in: */
/*   trade.c:1389 - int tradable(int int cntry, int int armynum) */
/*   trade.c:122 - int tradable(void) */
/* DUPLICATE: armyvalue found in: */
/*   trade.c:1451 - int armyvalue(int int cntry, int int unit) */
/*   trade.c:1204 - long armyvalue(void) */
/* DUPLICATE: takeback found in: */
/*   trade.c:1518 - void takeback(void) */
/*   trade.c:977 - int takeback(int int cntry, int int item, int long longval, int int extint, int int isup) */
/*   trade.c:1626 - void takeback(void) */
/*   trade.c:977 - int takeback(int int cntry, int int item, int long longval, int int extint, int int isup) */
/* DUPLICATE: setaside found in: */
/*   trade.c:1519 - void setaside(void) */
/*   trade.c:898 - int setaside(int int cntry, int int item, int long longval, int int extint, int int isup) */
/*   trade.c:1543 - else setaside(country,type2[type1[itemnum]],lvar1[itemnum],(int) */
/*   trade.c:898 - int setaside(int int cntry, int int item, int long longval, int int extint, int int isup) */
/*   trade.c:1784 - void setaside(void) */
/*   trade.c:898 - int setaside(int int cntry, int int item, int long longval, int int extint, int int isup) */
/* DUPLICATE: trademail found in: */
/*   trade.c:1621 - void trademail(void) */
/*   trade.c:1289 - int trademail(int int cntry1, int int cntry2, int int item1, int int item2, int long lvar1, int long lvar2, int long lvar3, int long lvar4) */
/* DUPLICATE: tradeit found in: */
/*   trade.c:1623 - long tradeit(void) */
/*   trade.c:1063 - int tradeit(int int cntry1, int int cntry2, int int item, int long longval, int int extra) */
